services:
  nginx:
    container_name: nginx
    build: .
    ports:
      - 80:80
      - 443:443
    networks:
      - auth_proxy_net

volumes:
  pgdata_auth_proxy_net:

networks:
  auth_proxy_net:
    external: true
